# Generated by Django 3.1 on 2020-08-28 09:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('contacts', models.CharField(max_length=70)),
                ('statistic_views', models.IntegerField(default=0)),
                ('passed_moderation', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('admins', models.ManyToManyField(related_name='moderated_places', to='user_auth.ProfileModel')),
                ('fav', models.ManyToManyField(related_name='favourites_places', to='user_auth.ProfileModel')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_places', to='user_auth.profilemodel')),
            ],
            options={
                'db_table': 'place',
            },
        ),
        migrations.CreateModel(
            name='SpecificityModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specificity_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'specificity',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='TypeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='ScheduleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mon_open', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('mon_close', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('tue_open', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('tue_close', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('wed_open', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('wed_close', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('thu_open', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('thu_close', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('fri_open', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('fri_close', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('sat_open', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('sat_close', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('sun_open', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('sun_close', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^(([0-1]{0,1}[0-9])|(2[0-3])):[0-5]{0,1}[0-9]$')])),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='place.placemodel')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
        migrations.AddField(
            model_name='placemodel',
            name='specificities',
            field=models.ManyToManyField(related_name='places', to='place.SpecificityModel'),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='tags',
            field=models.ManyToManyField(related_name='places', to='place.TagModel'),
        ),
        migrations.AddField(
            model_name='placemodel',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place', to='place.typemodel'),
        ),
        migrations.CreateModel(
            name='PhotoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='places\\img')),
                ('places', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='place.placemodel')),
            ],
            options={
                'db_table': 'photos',
            },
        ),
        migrations.CreateModel(
            name='CoordinatesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=20)),
                ('lng', models.CharField(max_length=20)),
                ('place', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='place.placemodel')),
            ],
            options={
                'db_table': 'coordinates',
            },
        ),
    ]
