# Generated by Django 3.1 on 2020-08-28 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatCommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('pyiachok_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_comments', to='event.pyiachokmodel')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_comments', to='user.profilemodel')),
            ],
            options={
                'db_table': 'chat_comment',
            },
        ),
    ]
